FROM node:26.1.0@sha256:f6f9fae352b319e817eec5efc7721b3f06bc53104f2f800d0f778f3915835804

WORKDIR /app/ui

COPY ui /app/ui

RUN npm install -g corepack@0.34.6 && corepack enable && pnpm install --frozen-lockfile

ENTRYPOINT ["pnpm", "start"]

